//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.BedAllotments = new HashSet<BedAllotment>();
            this.DoctorVisitPaymentDetails = new HashSet<DoctorVisitPaymentDetail>();
            this.LabPayments = new HashSet<LabPayment>();
            this.MedicalPaymentDetails = new HashSet<MedicalPaymentDetail>();
            this.PatientBills = new HashSet<PatientBill>();
            this.PatientVisits = new HashSet<PatientVisit>();
            this.ServicePayments = new HashSet<ServicePayment>();
            this.WardOrRoomChargeDetails = new HashSet<WardOrRoomChargeDetail>();
            this.DischargeSummaries = new HashSet<DischargeSummary>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> Doctor_ID { get; set; }
        public Nullable<int> Specialization_ID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<int> BranchDetails_ID { get; set; }
        public Nullable<long> PatientDetails_ID { get; set; }
        public Nullable<int> ShiftType_ID { get; set; }
        public int IsReferal { get; set; }
        public string ReferalDetails { get; set; }
        public int VisitStatus { get; set; }
        public Nullable<int> PatientType_ID { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
        public virtual PatientType PatientType { get; set; }
        public virtual ShiftType ShiftType { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual ICollection<BedAllotment> BedAllotments { get; set; }
        public virtual ICollection<DoctorVisitPaymentDetail> DoctorVisitPaymentDetails { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<MedicalPaymentDetail> MedicalPaymentDetails { get; set; }
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        public virtual ICollection<PatientVisit> PatientVisits { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual ICollection<WardOrRoomChargeDetail> WardOrRoomChargeDetails { get; set; }
        public virtual ICollection<DischargeSummary> DischargeSummaries { get; set; }
    }
}
