//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchDetail
    {
        public BranchDetail()
        {
            this.Appointments = new HashSet<Appointment>();
            this.EmployeeDetails = new HashSet<EmployeeDetail>();
            this.PatientBills = new HashSet<PatientBill>();
            this.ServiceSubCategories = new HashSet<ServiceSubCategory>();
            this.Wards = new HashSet<Ward>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public long PhoneNoPri { get; set; }
        public long PhoneNoSec { get; set; }
        public long MobileNo { get; set; }
        public long FaxNo { get; set; }
        public string EmailInfo { get; set; }
        public string EmailCustomerCare { get; set; }
        public string WebAddress { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<int> City_ID { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        public virtual ICollection<ServiceSubCategory> ServiceSubCategories { get; set; }
        public virtual ICollection<Ward> Wards { get; set; }
    }
}
