//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.BranchDetails = new HashSet<BranchDetail>();
            this.EmployeeDetails = new HashSet<EmployeeDetail>();
            this.PatientDetails = new HashSet<PatientDetail>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> State_ID { get; set; }
    
        public virtual ICollection<BranchDetail> BranchDetails { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
    }
}
