//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorVisitPaymentDetail
    {
        public long ID { get; set; }
        public decimal VisitAmount { get; set; }
        public long PaymentStatus { get; set; }
        public long PaymentReceivedBy { get; set; }
        public System.DateTime PaymentReceivedDate { get; set; }
        public decimal DiscountAmount { get; set; }
        public long DiscountedBy { get; set; }
        public string DiscountDescription { get; set; }
        public string PaymentDetails { get; set; }
        public Nullable<long> Doctor_ID { get; set; }
        public Nullable<int> PaymentMode_ID { get; set; }
        public Nullable<int> PaymentSection_ID { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentSection PaymentSection { get; set; }
    }
}
