//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorBillDetail
    {
        public long ID { get; set; }
        public decimal VisitCharge { get; set; }
        public decimal ConsultantCharge { get; set; }
        public decimal OperationCharge { get; set; }
        public decimal OtherChargeAmount { get; set; }
        public string OtherChargeDetails { get; set; }
        public System.DateTime CreateDate { get; set; }
        public decimal AdvancePayAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal DuesAmount { get; set; }
        public long PaidBy { get; set; }
        public System.DateTime PaidOn { get; set; }
        public long PaymentStatusID { get; set; }
        public Nullable<long> Doctor_ID { get; set; }
        public Nullable<long> PatientDetails_ID { get; set; }
        public Nullable<int> PatientType_ID { get; set; }
        public Nullable<int> PaymentMode_ID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
        public virtual PatientType PatientType { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
