//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.DoctorBillDetails = new HashSet<DoctorBillDetail>();
            this.DoctorVisitPaymentDetails = new HashSet<DoctorVisitPaymentDetail>();
            this.LabPayments = new HashSet<LabPayment>();
            this.MedicalPaymentDetails = new HashSet<MedicalPaymentDetail>();
            this.ServicePayments = new HashSet<ServicePayment>();
            this.ShiftDates = new HashSet<ShiftDate>();
            this.ShiftDays = new HashSet<ShiftDay>();
            this.ShiftTypes = new HashSet<ShiftType>();
        }
    
        public long ID { get; set; }
        public string OtherDetails { get; set; }
        public string RegistrationNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<long> EmployeeDetail_ID { get; set; }
        public bool Daywise { get; set; }
        public bool Datewise { get; set; }
        public Nullable<int> Qualification_ID { get; set; }
        public Nullable<int> Specialization_ID { get; set; }
        public string MorningShifDetails { get; set; }
        public string EveningShifDetails { get; set; }
        public string FormerlyAt { get; set; }
        public string VisitingConsultant { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<DoctorBillDetail> DoctorBillDetails { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual ICollection<DoctorVisitPaymentDetail> DoctorVisitPaymentDetails { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<MedicalPaymentDetail> MedicalPaymentDetails { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual ICollection<ShiftDate> ShiftDates { get; set; }
        public virtual ICollection<ShiftDay> ShiftDays { get; set; }
        public virtual ICollection<ShiftType> ShiftTypes { get; set; }
        public virtual Qualification Qualification1 { get; set; }
        public virtual Specialization Specialization1 { get; set; }
    }
}
