//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public EmployeeDetail()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Doctors1 = new HashSet<Doctor>();
            this.Doctors2 = new HashSet<Doctor>();
            this.DoctorVisitPaymentDetails = new HashSet<DoctorVisitPaymentDetail>();
            this.PatientBills = new HashSet<PatientBill>();
            this.RegistrationPaymentDetails = new HashSet<RegistrationPaymentDetail>();
            this.LabPayments = new HashSet<LabPayment>();
            this.LabPayments1 = new HashSet<LabPayment>();
            this.PatientVisits = new HashSet<PatientVisit>();
            this.ServicePayments = new HashSet<ServicePayment>();
            this.ServicePayments1 = new HashSet<ServicePayment>();
            this.WardOrRoomChargeDetails = new HashSet<WardOrRoomChargeDetail>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public long MobileNo { get; set; }
        public long OtherContactNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AadharNo { get; set; }
        public string VoterIDNo { get; set; }
        public string DriverLicenceNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Password { get; set; }
        public Nullable<int> BranchDetail_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> EmployeeType_ID { get; set; }
        public Nullable<int> Title_ID { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Doctor> Doctors1 { get; set; }
        public virtual ICollection<Doctor> Doctors2 { get; set; }
        public virtual ICollection<DoctorVisitPaymentDetail> DoctorVisitPaymentDetails { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        public virtual ICollection<RegistrationPaymentDetail> RegistrationPaymentDetails { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<LabPayment> LabPayments1 { get; set; }
        public virtual ICollection<PatientVisit> PatientVisits { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments1 { get; set; }
        public virtual ICollection<WardOrRoomChargeDetail> WardOrRoomChargeDetails { get; set; }
    }
}
