//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabCategory
    {
        public LabCategory()
        {
            this.LabPayments = new HashSet<LabPayment>();
            this.LabTests = new HashSet<LabTest>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<LabTest> LabTests { get; set; }
    }
}
