//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        public LabTest()
        {
            this.LabPayments = new HashSet<LabPayment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal LabTestCost { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<int> LabCategory_ID { get; set; }
    
        public virtual LabCategory LabCategory { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
    }
}
