//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public PatientVisit()
        {
            this.LabPayments = new HashSet<LabPayment>();
            this.MedicalPaymentDetails = new HashSet<MedicalPaymentDetail>();
            this.PatientBills = new HashSet<PatientBill>();
            this.ServicePayments = new HashSet<ServicePayment>();
        }
    
        public int ID { get; set; }
        public System.DateTime VisitedDate { get; set; }
        public int PatientStatus { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public decimal RegistrationAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PayAmount { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
        public Nullable<int> PaymentMode_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<MedicalPaymentDetail> MedicalPaymentDetails { get; set; }
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
    }
}
