//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBill
    {
        public long ID { get; set; }
        public decimal ServiceAmount { get; set; }
        public decimal LabAmount { get; set; }
        public decimal WardAmount { get; set; }
        public decimal MedicalAmount { get; set; }
        public decimal RegistrationAmount { get; set; }
        public decimal DoctorVisitAmount { get; set; }
        public decimal OtherChargeAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AdvancePaymentAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal DuesAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentDetails { get; set; }
        public Nullable<int> BranchDetail_ID { get; set; }
        public Nullable<long> EmployeeDetail_ID { get; set; }
        public Nullable<int> PaymentMode_ID { get; set; }
        public Nullable<int> PaymentSection_ID { get; set; }
        public Nullable<int> PatientVisit_ID { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual PatientVisit PatientVisit { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentSection PaymentSection { get; set; }
    }
}
