//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public PatientVisit()
        {
            this.RegistrationPaymentDetails = new HashSet<RegistrationPaymentDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime VisitedDate { get; set; }
        public int PatientStatusID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public decimal RegistrationAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PayAmount { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
        public Nullable<int> PaymentMode_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual PatientStatu PatientStatu { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual ICollection<RegistrationPaymentDetail> RegistrationPaymentDetails { get; set; }
    }
}
