//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public PatientDetail()
        {
            this.Appointments = new HashSet<Appointment>();
            this.DischargeSummaries = new HashSet<DischargeSummary>();
            this.DoctorBillDetails = new HashSet<DoctorBillDetail>();
        }
    
        public long ID { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string FatherOrHusbandName { get; set; }
        public long ContactNo { get; set; }
        public long OtherContactNo { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<int> City_ID { get; set; }
        public int MarritalStatus { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<DischargeSummary> DischargeSummaries { get; set; }
        public virtual ICollection<DoctorBillDetail> DoctorBillDetails { get; set; }
    }
}
