//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientType
    {
        public PatientType()
        {
            this.Appointments = new HashSet<Appointment>();
            this.DoctorBillDetails = new HashSet<DoctorBillDetail>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<DoctorBillDetail> DoctorBillDetails { get; set; }
    }
}
