//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStau
    {
        public PaymentStau()
        {
            this.DoctorBillDetails = new HashSet<DoctorBillDetail>();
            this.LabPayments = new HashSet<LabPayment>();
            this.MedicalPaymentDetails = new HashSet<MedicalPaymentDetail>();
            this.RegistrationPaymentDetails = new HashSet<RegistrationPaymentDetail>();
            this.ServicePayments = new HashSet<ServicePayment>();
            this.WardOrRoomChargeDetails = new HashSet<WardOrRoomChargeDetail>();
        }
    
        public long ID { get; set; }
        public string Details { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<DoctorBillDetail> DoctorBillDetails { get; set; }
        public virtual ICollection<LabPayment> LabPayments { get; set; }
        public virtual ICollection<MedicalPaymentDetail> MedicalPaymentDetails { get; set; }
        public virtual ICollection<RegistrationPaymentDetail> RegistrationPaymentDetails { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual ICollection<WardOrRoomChargeDetail> WardOrRoomChargeDetails { get; set; }
    }
}
