//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMode
    {
        public PaymentMode()
        {
            this.DoctorBillDetails = new HashSet<DoctorBillDetail>();
            this.DoctorVisitPaymentDetails = new HashSet<DoctorVisitPaymentDetail>();
            this.MedicalPaymentDetails = new HashSet<MedicalPaymentDetail>();
            this.PatientBills = new HashSet<PatientBill>();
            this.PatientVisits = new HashSet<PatientVisit>();
            this.RegistrationPaymentDetails = new HashSet<RegistrationPaymentDetail>();
        }
    
        public int ID { get; set; }
        public string Mode { get; set; }
    
        public virtual ICollection<DoctorBillDetail> DoctorBillDetails { get; set; }
        public virtual ICollection<DoctorVisitPaymentDetail> DoctorVisitPaymentDetails { get; set; }
        public virtual ICollection<MedicalPaymentDetail> MedicalPaymentDetails { get; set; }
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        public virtual ICollection<PatientVisit> PatientVisits { get; set; }
        public virtual ICollection<RegistrationPaymentDetail> RegistrationPaymentDetails { get; set; }
    }
}
