//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        public RoomDetail()
        {
            this.BedAllotments = new HashSet<BedAllotment>();
            this.WardOrRoomChargeDetails = new HashSet<WardOrRoomChargeDetail>();
        }
    
        public int ID { get; set; }
        public string Details { get; set; }
        public int TotalBed { get; set; }
        public Nullable<int> Ward_ID { get; set; }
        public string RoomNo { get; set; }
        public decimal RoomCost { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<BedAllotment> BedAllotments { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual ICollection<WardOrRoomChargeDetail> WardOrRoomChargeDetails { get; set; }
    }
}
