//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSubCategory
    {
        public ServiceSubCategory()
        {
            this.ServicePayments = new HashSet<ServicePayment>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public decimal ServiceCharges { get; set; }
        public int AverageDuration { get; set; }
        public Nullable<int> BranchDetail_ID { get; set; }
        public Nullable<long> Service_ID { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual Service Service { get; set; }
    }
}
