//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ServicePayments = new HashSet<ServicePayment>();
            this.ServiceSubCategories = new HashSet<ServiceSubCategory>();
        }
    
        public long ID { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ServicePayment> ServicePayments { get; set; }
        public virtual ICollection<ServiceSubCategory> ServiceSubCategories { get; set; }
    }
}
