//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftType
    {
        public ShiftType()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ShiftDates = new HashSet<ShiftDate>();
            this.ShiftDays = new HashSet<ShiftDay>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Doctor_ID { get; set; }
        public decimal ShiftCharge { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<ShiftDate> ShiftDates { get; set; }
        public virtual ICollection<ShiftDay> ShiftDays { get; set; }
    }
}
