//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardOrRoomChargeDetail
    {
        public long ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal RoomCharge { get; set; }
        public string OtherDetails { get; set; }
        public decimal OtherCharge { get; set; }
        public decimal DiscountAmount { get; set; }
        public long DiscountedBy { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<int> RoomDetails_ID { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual RoomDetail RoomDetail { get; set; }
    }
}
