//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public Ward()
        {
            this.RoomDetails = new HashSet<RoomDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TotalNoOfBed { get; set; }
        public string OtherDetails { get; set; }
        public Nullable<int> BranchDetail_ID { get; set; }
        public Nullable<int> WardCategory_ID { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual ICollection<RoomDetail> RoomDetails { get; set; }
        public virtual WardCategory WardCategory { get; set; }
    }
}
